#!/usr/bin/tclsh

set input "RDZFIEUgRDZFaiBTRSBCIERFQzo/OGogU0UgQyA6PzRDaiBTRSBJIDo/NTZJaiBTRSAzIFEtU0IgNkJGMj0gLVM0UWogU0UgNSAsODZFRCBERTU6Py5qU0UgNSAsREE9OkUgUzUgUVEualNFID0gX2ogU0UgOSBfaiBTRSA+ICw9QzZBNjJFIGJfX19fIF8uaj0yQUE2PzUgPCBfaiA3QEMgTFNFIDkgX04gTFM5IGsgLFNCID02PzhFOSBTNS5OIExTQyA5TiBMU0UgSiAsPVNJIFM+IFM9LmpTRSA0PjUgLD1TSSBTNSBTOS5qREg6RTQ5IFM0PjUgTFFaUSBMPVNFID4gUz0gLDZJQUMgV1NKIFogYFhUYWRlLk4gUVxRIEw9U0UgPiBTPSAsNklBQyBXU0ogXCBgWFRhZGUuTiBRbVEgTFNDID1OIFFrUSBMU0MgPSBcYE4gUV1RIExBRkVEIFw/QD82SD06PzYgLDdAQz4yRSBUNCBTSi5OIFEsUSBMOjcgTFNKIGxsIF9OIExTRSA4IGBqIEg5Oj02IExTOE4gTFNDIDlqIFNFIDQgLFNCIFNJIFM1IFM5Lmo6NyBMLFMzTCxOIC5OIExTQyA4TiA2PUQ2OjcgTCxTM0wuTi5OIExTQyA4IFxgTk5OIDY9RDYgTD0yQUE2PzUgPCAsNklBQyBTOSBcIGAuak5OIFEuUSBMOjcgTFNKTiBMU0UgOSAsPVNJIFM8IDY/NS5qTmogU0UgPCAsPUMyPzg2IFM8IF8gNj81XGAuak4gNTY3MkY9RSBMTk5O"

set input [binary decode base64 $input]

set input [split $input ""]
set s 13
set output ""

foreach char $input {
    set a [scan $char %c]
    if {$a > 33 && $a < 127} {
        set a [expr {($a + 47 - 33) % 94 + 33}]
    }

    set char [format %c $a]

    append output $char
}

eval $output